In [1]:
import pandas as pd
pd.read_csv("C:/Users/alexs/OneDrive/Desktop/MLB/data/pitching24.csv", encoding = "latin1")

,Rk,Player,Age,Team,Lg,WAR,W,L,W-L%,ERA,...,HardH%,LD%,GB%,FB%,GB/FB,WPA,cWPA,RE24,Awards.1,-9999
0,1,Logan Gilbert,27,SEA,AL,2.8,9,12,0.429,3.23,...,39.4,23.8,44.1,24.4,0.80,1.3,0.50%,17.91,ASCYA-6,gilbelo01
1,2,Seth Lugo,34,KCR,AL,5.3,16,9,0.640,3.00,...,39.0,24.9,43.6,25.8,0.79,3.4,2.10%,33.49,ASCYA-2MVP-15GG,lugose01
2,3,Logan Webb,27,SFG,NL,3.7,13,10,0.565,3.47,...,46.3,23.2,57.1,17.3,1.33,1.3,0.90%,16.55,ASCYA-6,webblo01
3,4,Zack Wheeler,34,PHI,NL,6.1,16,7,0.696,2.57,...,33.7,20.9,42.5,26.0,0.75,4.1,2.60%,39.88,ASCYA-2MVP-12,wheelza01
4,5,Aaron Nola,31,PHI,NL,3.6,14,8,0.636,3.57,...,38.3,24.6,44.2,24.4,0.80,1.5,0.90%,14.68,CYA-11,nolaaa01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,1090,Miguel SanÃ³,31,LAA,AL,0.0,0,0,NaN,0.00,...,0.0,0.0,100.0,0.0,NaN,0.0,0.00%,0.77,NaN,sanomi01
849,1091,Luis Torrens,28,NYM,NL,0.0,0,0,NaN,0.00,...,100.0,0.0,100.0,0.0,NaN,0.0,0.00%,0.23,NaN,torrelu01
850,1092,Patrick Wisdom,32,CHC,NL,0.0,0,0,NaN,0.00,...,50.0,0.0,100.0,0.0,NaN,0.0,0.00%,-0.49,NaN,wisdopa01
851,1093,Carl Edwards Jr.,32,SDP,NL,0.0,0,0,NaN,NaN,...,100.0,0.0,100.0,0.0,NaN,-0.3,-0.30%,-2.27,NaN,edwarca01
852,1094,Wander Suero,32,HOU,AL,0.0,0,1,0.000,NaN,...,100.0,100.0,0.0,0.0,0.00,-0.2,-0.10%,-0.76,NaN,suerowa01